#!/bin/bash

run_command() {
  COMMAND=$1
  FILE_PREFIX=$2
  MODE=$3
  echo "$COMMAND" &> outputs/${FILE_PREFIX}:COMMAND
  faketime '2030-01-01 08:30:00' bash -c "$COMMAND" &> outputs/${FILE_PREFIX}:${MODE:=EMPTY}
}

mkdir outputs

mkdir testdir
chmod go-rwx testdir
echo "Lorem Ipsum" > testdir/A.txt

for R in "" "r"; do
  for W in "" "w"; do
    for X in "" "x"; do
      MODE=$R$W$X
      chmod u=${MODE} testdir

      run_command 'stat testdir' "0_stat_testdir" $MODE

      run_command 'ls -l testdir' "1_ls_l_test_dir" $MODE

      run_command 'cat testdir/A.txt' "2_cat_Atxt" $MODE

      run_command 'echo "New file" > testdir/B.txt' "3_echo_Btxt" $MODE

      run_command 'cd testdir' "4_cd" $MODE
    done
  done
done

chmod u+wx testdir
rm -rf testdir

# Normalize datetime
cd outputs
fastmod '\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d.\d\d\d\d\d\d\d\d\d -0400' '2030-01-01 08:30:00.000000000 -0000' --accept-all
