#!/bin/bash
set eiu

chmod u+rwx testdir
rm -rf testdir
mkdir testdir

rm -rf outputs
mkdir outputs
echo "Lorem Ipsum" > testdir/A.txt


chmod go-rwx testdir

run_command() {
  COMMAND=$1
  FILE_PREFIX=$2
  MODE=$3
  echo "$COMMAND" &> outputs/${FILE_PREFIX}:COMMAND
  bash -c "$COMMAND" &> outputs/${FILE_PREFIX}:${MODE:=EMPTY}
}

for R in "" "r"; do
  for W in "" "w"; do
    for X in "" "x"; do
      MODE=$R$W$X
      chmod u=${MODE} testdir

      run_command 'stat testdir' "0_stat_testdir" $MODE

      run_command 'ls -l testdir' "1_ls_l_test_dir_" $MODE

      run_command 'cat testdir/A.txt' "2_cat_Atxt" $MODE

      run_command 'echo "New file" > testdir/B.txt' "3_echo_Btxt" $MODE
    done
  done
done

# Normalize datetime
cd outputs
fastmod '\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d.\d\d\d\d\d\d\d\d\d -0400' '2030-01-01 08:30:00.000000000 -0000' --accept-all
